### 注册用户
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "test",
  "password": "123456",
  "email": "test@example.com"
}

### 用户登录
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "zl",
  "password": "123456"
}

### 获取用户信息
GET http://localhost:8080/api/user/test